wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.12
    start_time: 1671622416
    t:
      1:
      - 55
      2:
      - 55
      4: 3.9.12
      5: 0.12.17
      8:
      - 2
      - 5
